[package]
name = "crash_course"
version = "0.1.0"
edition = "2018"
crate-type = ["cdylib", "rlib"]



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



